for test
RuslanIbIsh/multithreading01 pull request #2
Opened 2021-02-24 11:33 UTC by RuslanIbIsh

2021-02-24 15:26 UTC, Ilya-brinchuk approved these changes

2021-02-24 15:40 UTC, Sofasmile requested changes

2021-02-24 15:40 UTC, Sofasmile commented on src/main/java/com/iri/multithreading/concurrentexecutor/CallableExecutor.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(5);
5 краще виести в константу

2021-02-24 15:40 UTC, Sofasmile commented on src/main/java/com/iri/multithreading/util/ListFillerUtil.java
> +public class ListFillerUtil {
варто пам'ятати про принципи SOLID
в класа повинна бути одна зона відповідальності, а в даному випадку ми створюємо список з числами і список з  Callable. Виглядає не зовсім ок.
Пропозиція винести створення списка List<Callable<Integer>>  як приватний метод, безпоседеньо в той клас, де ми це використовуємо, тобто в CallableExecutor)

2021-02-24 15:40 UTC, Sofasmile commented on src/main/java/com/iri/multithreading/util/ListFillerUtil.java
> +        listCallable.add(new SumSublistCallableImpl(bigDataList.subList(800_000, 1_000_000)));
спробуй оптимізувати цей. А що якщо нам потрібно буде створити списки по 100_000 елементів в кожному? Ми будемо робити це в ручну? Чи можливо краще задати якийсь крок і робити це в циклі?

2021-02-24 15:40 UTC, Sofasmile commented on src/test/java/com/iri/multithreading/concurrentexecutor/CallableExecutorTest.java
> +import static org.junit.Assert.*;
використовувати автоімпорти погана практика, тому давай позбудемось їх))

2021-02-24 15:40 UTC, Sofasmile commented on src/test/java/com/iri/multithreading/concurrentexecutor/CallableExecutorTest.java
> +}
варто додати пусту строку)

2021-02-24 15:40 UTC, Sofasmile commented on src/test/java/com/iri/multithreading/concurrentforkjoin/CallableForkJoinerTest.java
> +}
і тут також))

2021-02-24 15:40 UTC, Sofasmile commented on src/test/java/com/iri/multithreading/concurrentexecutor/CallableExecutorTest.java
> +    public void whenSum() {
на майбутнє, коли будеш писати тести до тестових завдань, одного тестового методу замало, варто розглядати більше сценаріїв поведінки. Але поки можеш залишити як є

2021-02-24 15:58 UTC, RuslanIbIsh commented on src/main/java/com/iri/multithreading/concurrentexecutor/CallableExecutor.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(5);
done

2021-02-25 07:23 UTC, RuslanIbIsh commented on src/main/java/com/iri/multithreading/util/ListFillerUtil.java
> +public class ListFillerUtil {
done

2021-02-25 07:23 UTC, RuslanIbIsh commented on src/main/java/com/iri/multithreading/util/ListFillerUtil.java
> +        listCallable.add(new SumSublistCallableImpl(bigDataList.subList(800_000, 1_000_000)));
done

2021-02-25 07:26 UTC, RuslanIbIsh commented on src/test/java/com/iri/multithreading/concurrentexecutor/CallableExecutorTest.java
> +import static org.junit.Assert.*;
done

2021-02-25 07:26 UTC, RuslanIbIsh commented on src/test/java/com/iri/multithreading/concurrentexecutor/CallableExecutorTest.java
> +}
done

2021-02-25 07:27 UTC, RuslanIbIsh commented on src/test/java/com/iri/multithreading/concurrentforkjoin/CallableForkJoinerTest.java
> +}
done

2021-02-25 07:34 UTC, RuslanIbIsh commented on src/test/java/com/iri/multithreading/concurrentexecutor/CallableExecutorTest.java
> +    public void whenSum() {
Спасибо, понял

2021-02-25 07:58 UTC, Sofasmile requested changes

2021-02-25 07:58 UTC, Sofasmile commented on src/main/java/com/iri/multithreading/concurrentexecutor/CallableExecutor.java
>      public int getSumSublist() {
давай на вхід цьому методі ми будемо приймати ліст з числами, так наш код буде більш гнучким, і ми не будемо хардкодити список в методі)
Те ж саме стосується Fork Join)

2021-02-25 12:10 UTC, Sofasmile approved these changes

2021-02-25 13:03 UTC, RuslanIbIsh commented on src/main/java/com/iri/multithreading/concurrentexecutor/CallableExecutor.java
>      public int getSumSublist() {
done

2021-02-25 13:03 UTC, merged